name: 'test'
description: 'Testing'
inputs:
  GITHUB_TOKEN:
    required: true
runs:
  using: "composite"
  steps: 
    - run: GITHUB_TOKEN=${{ inputs.GITHUB_TOKEN }} $GITHUB_ACTION_PATH/action/script1.sh
      shell: bash
